### ISSUE TITLE
New section: Service discovery

### ISSUE THREAD

**Issue by tt** [brandur/microservices#10]
> Components should discover one another using a means of service discovery.

(This is somewhat at odds with [the backing services of a twelve-factor app](https://12factor.net/backing-services).)

**Comment by brandur** [comment]
Yeah, this is one that we took for granted at Heroku because you kind of get it for free with the router, but it's definitely worth calling out explicitly because most people aren't in that type of situation. We should probably be pretty liberal about what we prescribe; it could be the Heroku router, Consul, an ELB, or maybe even basic DNS.

**Comment by tt** [comment]
I see the router as a poor man's approach. It works but it performs much worse than the alternatives.

I would personally prefer something based on DNS because it requires nothing not already included in a decent standard library. I think we can mention this as an example more than a required implementation, though.

**Comment by brandur** [comment]
> I would personally prefer something based on DNS because it requires nothing not already included in a decent standard library. I think we can mention this as an example more than a required implementation, though.

Yeah, that works for me.
