### ISSUE TITLE
Prescribe shared resources over libraries

### ISSUE THREAD

**Issue by tt** [brandur/microservices#2]
Somewhat similar to #1, I wonder if it makes sense to prescribe shared resources and only to some extend shared libraries. To me it's more important that all your logs drain to the same destination than to use the same tool for logging (although each class of component should converge ultimately).

**Comment by brandur** [comment]
@tt This is related to the last part of this sentence right?

> Standardize on languages, frameworks, and even libraries

I didn't want this to appear too prescriptive, but I was kind of hoping to build the idea that the more things you have in common, the easier software development is going to be. Along with just getting service re-use, any single developer can move between teams and be productive quickly because their standard toolchain is already there.

I added a rewording of the section in #5. Thoughts on that?

**Comment by tt** [comment]
Yes, that's a lot better. One of the reasons I like microservices is that it encourages experimentation and specialization which are both good reasons to occasionally allow inconsistencies.
